apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "metrics"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
---
# 2. METRICS BACKEND
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      enableServiceLinks: false
      containers:
      - name: backend
        image: metrics-backend:latest
        imagePullPolicy: Never # Tells K8s to use your local docker build
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis" # Matches the Redis Service name above
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_METRICS_CHANNEL
          value: "metrics:live"
        - name: POSTGRES_DSN
          value: "postgresql://postgres:postgres@postgres:5432/metrics"
        - name: POSTGRES_TABLE
          value: "metrics_snapshots"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort # This allows you to visit http://localhost:8000 on your machine
---
# 3. METRICS AGENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
spec:
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: metrics-agent:latest
        imagePullPolicy: Never
        # Passing your flags as arguments
        args: ["--backend-url", "http://backend:8000", "--interval", "2"]
---
# 4. DASHBOARD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      enableServiceLinks: false
      containers:
      - name: dashboard
        image: metrics-dashboard:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_BASE_URL
          value: "http://backend:8000"
        - name: DASHBOARD_AUTH_ENABLED
          value: "true"
        - name: DASHBOARD_USERNAME
          value: "admin"
        - name: DASHBOARD_PASSWORD
          value: "admin"
        - name: DASHBOARD_SESSION_SECRET
          value: "dev-dashboard-secret"
        - name: DASHBOARD_MAX_POINTS
          value: "150"
        - name: DASHBOARD_ALERT_MINUTES
          value: "60"
        - name: DASHBOARD_PERF_POLL_SECONDS
          value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  selector:
    app: dashboard
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30430
  type: NodePort # Access dashboard via http://localhost:8080 (Docker Desktop) or minikube service dashboard --url